/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiPlannerRouteImport } from './routes/api/planner'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiEmailRouteImport } from './routes/api/email'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlannerRoute = ApiPlannerRouteImport.update({
  id: '/api/planner',
  path: '/api/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailRoute = ApiEmailRouteImport.update({
  id: '/api/email',
  path: '/api/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/email': typeof ApiEmailRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/planner': typeof ApiPlannerRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/email': typeof ApiEmailRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/planner': typeof ApiPlannerRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/email': typeof ApiEmailRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/planner': typeof ApiPlannerRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/responsible-ai'
    | '/api/chat'
    | '/api/email'
    | '/api/meetings'
    | '/api/planner'
    | '/api/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/responsible-ai'
    | '/api/chat'
    | '/api/email'
    | '/api/meetings'
    | '/api/planner'
    | '/api/research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/responsible-ai'
    | '/api/chat'
    | '/api/email'
    | '/api/meetings'
    | '/api/planner'
    | '/api/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  MeetingsRoute: typeof MeetingsRoute
  PlannerRoute: typeof PlannerRoute
  ResearchRoute: typeof ResearchRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmailRoute: typeof ApiEmailRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiPlannerRoute: typeof ApiPlannerRoute
  ApiResearchRoute: typeof ApiResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planner': {
      id: '/api/planner'
      path: '/api/planner'
      fullPath: '/api/planner'
      preLoaderRoute: typeof ApiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email': {
      id: '/api/email'
      path: '/api/email'
      fullPath: '/api/email'
      preLoaderRoute: typeof ApiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  MeetingsRoute: MeetingsRoute,
  PlannerRoute: PlannerRoute,
  ResearchRoute: ResearchRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmailRoute: ApiEmailRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiPlannerRoute: ApiPlannerRoute,
  ApiResearchRoute: ApiResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
